---
abstract: 'check whether a given value is a valid country code'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-WithYAML-Plugin-Country
requires:
  Data::Validate::WithYAML: 0.11
  Locale::Country::Multilingual: 0
resources:
  bugtracker: http://github.com/reneeb/Data-Validate-WithYAML-Plugin-Country/issues
  homepage: http://github.com/reneeb/Data-Validate-WithYAML-Plugin-Country
  repository: git://github.com/reneeb/Data-Validate-WithYAML-Plugin-Country.git
version: 0.02
